rng_seed: 1234

ui:
  screen_width: 1280
  screen_height: 720
  left_panel_percentage: 0.8
  topleft_preview_percentage: 0.7
  minimap:
    room_scale: 0.15
    corridor_scale: 0.075
assets: './assets'

game:
  stress:
    movement: 1
    turn: 2
    disarm_trap: -5
    trigger_trap: 7
    loot_treasure: -7
    trigger_trapped_treasure: 12
    no_inspect_treasure: -5
    ignore_treasure: 5
    hero_kill_enemy: -10
    enemy_kill_hero: 50
    passing: 10
    switch_position: 10