rng_seed: 1234
server_ip: '10.60.19.36'
server_port: 8080
username: 'gallorob'

ui:
  screen_width: 1280
  screen_height: 720
  left_panel_percentage: 0.8
  topleft_preview_percentage: 0.7
  minimap:
    room_scale: 0.15
    corridor_scale: 0.075
assets:
  dungeon_dir: './assets/dungeon_assets'
  logo: './assets/dungeon_despair_logo.png'
  screens:
    background: './assets/screens/background.png'
    gameover: './assets/screens/gameover.png'
  icons:
    combat:
      attacking: './assets/icons/attacking_icon.png'
      moving: './assets/icons/moving_icon.png'
      targeted: './assets/icons/targeted_icon.png'
    modifiers:
      bleed: './assets/icons/bleed_icon.png'
      heal: './assets/icons/heal_icon.png'
      stun: './assets/icons/stun_icon.png'
      scare: './assets/icons/scare_icon.png'

game:
  stress:
    movement: 1
    turn: 2
    disarm_trap: -5
    trigger_trap: 7
    loot_treasure: -7
    trigger_trapped_treasure: 12
    no_inspect_treasure: -5
    ignore_treasure: 5
    enemy_dies: -10
    hero_dies: 50
    passing: 10
    switch_position: 10
  sim_depth: 5
  diff_cycle: 5
  difficulties: ['very easy', 'easy', 'medium', 'hard', 'very hard']

gen:
  llm_model: 'qwen2.5:latest'
  llm_sysprompt: 'assets/llm_prompts/herogen_prompt'
  llm_usrmsg: 'I want the current {difficult} hero to have {n_attacks} different and unique attacks. Take the initiative and just make content.'
  temperature: 0.6
  top_p: 0.2
  top_k: 10
